name: anton_zyryanov_barcode_scanner
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_svg: ^2.0.10
  mobile_scanner: ^7.1.4
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  bloc_test: ^9.1.0
  mockito: ^5.4.0
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/home_page/
    - assets/images/paywall/
    - assets/images/handbook/tab_bar_icons/
    - assets/images/handbook/sections/
    - assets/images/handbook/sections/1/
    - assets/images/handbook/sections/2/
    - assets/images/handbook/sections/3/
    - assets/images/handbook/sections/4/
    - assets/images/handbook/sections/5/
    - assets/images/icons/
    - assets/images/errors/
    - assets/images/loader/
    - assets/data/1/section.json
    - assets/data/2/section.json
    - assets/data/3/section.json
    - assets/data/4/section.json
    - assets/data/5/section.json


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon/app_icon.jpg"
  min_sdk_android: 21
